### ISSUE TITLE
Update address format in OAS

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#104]
Update IP address format in 
- [ ] serviceList
- [ ] OAS
- [ ] CONFIGfile

from e.g.:
```
new-application-address:
  type: string
  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  description: >
    'IP address of application that shall be target of the handover process	
    update or create [/core-model-1-4:control-construct/logical-termination-point=*-0-0-1-tcp-c-0010/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]'
```
to 
```
new-application-address:
  type: object
  minProperties: 1
  maxProperties: 1
  additionalProperties: false
  properties:
    ip-address:
      type: object
        minProperties: 1
        additionalProperties: false
        properties:
          ipv-4-address:
             type: string
             pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
             description: >
               'IPv4 address of application that shall be target of the handover process
               update or create [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-nr-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]'
    domain-name:
      type: string
      pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
      description: >
        'Domain name of application that shall be target of the handover process
         update or create [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-nr-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name]'
```
