### ISSUE TITLE
domain-name to be added

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#129]
Data structure of the TcpClient and TcpServer got complemented by a domainName attribute for preparing for potential future appliance of a DNS function.

The following changes have to be made on the specifications:
- [x] OAS:
  - [x] all service bodies containing *address and *port
  - [x] all service body examples containing *address and *port
  - [x] all service response bodies containing *address and *port
  - [x] all service response body examples containing *address and *port
  - [x] all callbacks headline address descriptions referencing into the data structure of the HttpClient
  - [x] all callbacks headline address descriptions referencing into body of initiating request
  - [x] all callbacks bodies containing *address and *port
  - [x] all callbacks body examples containing *address and *port
  - [x] all callbacks response bodies containing *address and *port
  - [x] all callbacks response body examples containing *address and *port
  - [ ] /v1/list-ltps-and-fcs response body core-model-1-4:control-construct::logical-termination-point::layer-protocol oneOf TcpServer::tcp-server-interface-1-0:tcp-server-interface-pac::tcp-server-interface-configuration (see example below)
  - [ ] /v1/list-ltps-and-fcs response body core-model-1-4:control-construct::logical-termination-point::layer-protocol oneOf TcpClient::tcp-client-interface-1-0:tcp-client-interface-pac::tcp-client-interface-configuration
  - [ ] control-construct :: tcp-server
  - [ ] control-construct :: tcp-client

New TCP/IP address in **service bodies**:
```
new-application-address:
  type: object
  minProperties: 1
  maxProperties: 1
  additionalProperties: false
  properties:
    ip-address:
      type: object
      minProperties: 1
      additionalProperties: false
      properties:
        ipv-4-address:
          type: string
          pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
          description: >
            'IPv4 address of application that shall be target of the handover process
            update or create [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-nr-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]'
    domain-name:
      type: string
      pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
      description: >
        'Domain name of application that shall be target of the handover process
        update or create [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-nr-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name]'
new-application-port:
  type: integer
  minimum: 0
  maximum: 65535
  description: >
    'Port of application that shall be target of the handover process
    update or create [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-nr-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]'
```

Old TCP/IP address in **service bodies**:
```
new-application-address:
  type: string
  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  description: >
    'IP address of application that shall be target of the handover process
    update or create [/core-model-1-4:control-construct/logical-termination-point=*-0-0-1-tcp-c-0010/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]'
new-application-port:
  type: integer
  minimum: 0
  maximum: 65535
  description: >
    'Port of application that shall be target of the handover process
    update or create [/core-model-1-4:control-construct/logical-termination-point=*-0-0-1-tcp-c-0010/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]'
```
New **example**:
````
new-application-address:
  ip-address:
    ipv-4-address: '10.118.125.157'
new-application-port: 7000
````
Old **example**:
````
new-application-address: '10.118.125.157'
new-application-port: 7000
````

New /v1/list-ltps-and-fcs :: ... :: **tcp-server-interface-configuration**
````
tcp-server-interface-configuration:
  type: object
  required:
    - local-address
    - local-port
  properties:
    local-address:
      type: object
      minProperties: 1
      additionalProperties: false
      properties:
        ipv-4-address:
          type: string
        domain-name:
          type: string
    local-port:
      type: integer
````
Old /v1/list-ltps-and-fcs :: ... :: **tcp-server-interface-configuration**
````
tcp-server-interface-configuration:
            type: object
            required:
              - local-address
              - local-port
            properties:
              local-address:
                type: object
                properties:
                  ipv-4-address:
                    type: string
              local-port:
                type: integer
````

New /v1/list-ltps-and-fcs :: ... ::**tcp-client-interface-configuration**
````
tcp-client-interface-configuration:
  type: object
  required:
    - remote-address
    - remote-port
  properties:
    remote-address:
      type: object
      minProperties: 1
      maxProperties: 1
      additionalProperties: false
      properties:
        ip-address:
          type: object
          minProperties: 1
          additionalProperties: false
          properties:
            ipv-4-address:
              type: string
        domain-name:
          type: string
    remote-port:
      type: integer
````
Old /v1/list-ltps-and-fcs :: ... ::**tcp-client-interface-configuration**
````
tcp-client-interface-configuration:
  type: object
  required:
    - remote-address
    - remote-port
  properties:
    remote-address:
      type: object
      required:
        - ip-address
      properties:
        ip-address:
          type: object
          required:
            - ipv-4-address
          properties:
            ipv-4-address:
              type: string
    remote-port:
      type: integer
````
