### ISSUE TITLE
Pattern to UUID field to control-construct

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#137]
Pattern and example shall be added to the UUID field at the control-construct shall be added, if individual:

New /core-model-1-4:control-construct:  core-model-1-4:control-construct::uuid
````
uuid:
  type: string
  pattern: '^([a-z]{2,6})-([0-9]+)-([0-9]+)-([0-9]+)$'
  example: 'ro-1-0-0'
````
Old /core-model-1-4:control-construct:  core-model-1-4:control-construct::uuid
````
uuid:
  type: string
