### ISSUE TITLE
Include requestBody and Update Response logic for the service /v1/list-applications

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#218]
As per the decision taken in this issue https://github.com/openBackhaul/RegistryOffice/issues/186 , this service will contain the following optional requestBody , 
```
properties:
                required-protocol:
                  type: string
                  enum:
                  - 'HTTP'
                  - 'HTTPS'
                  description: >
                    'Whenever sent, addresses for this protocol shall be provided. 
                    If requestBody or required-protocol attribute not sent, responseBody shall not contain any TCP/IP addresses.'
              example:
                required-protocol: 'HTTP'
```

If the service initiated without a requestBody , then only the following 2 attributes needs to be provided , 
```
- application-name
- application-release-number
```

If the service initiated without a requestBody , then only the following 4 attributes needs to be provided , 
```
- application-name
- application-release-number
- application-address
- application-port
```
If the tcp-client of an application doesn’t have the details of the requested protocol , then no need to include that application as a part of the response.
Please refer the conversation https://github.com/openBackhaul/RegistryOffice/pull/193#issuecomment-1315619666.
