### ISSUE TITLE
Wrong keywords in forwardingList?

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/RegistryOffice#390]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: ServiceRequestCausesFcUpdateRequest
    uuid: ro-2-0-1-op-fc-bm-008
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ro-2-0-1-op-s-bm-009
      fc-port-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ro-2-0-1-op-s-bm-009
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - service-name: /v1/register-application
        uuid: ro-2-0-1-op-s-is-001
      - service-name: /v1/regard-updated-approval-status
        uuid: ro-2-0-1-op-s-is-003
      - service-name: /v1/notify-deregistrations
        uuid: ro-2-0-1-op-s-is-007
      - service-name: /v1/notify-approvals
        uuid: ro-2-0-1-op-s-is-008
      - service-name: /v1/notify-withdrawn-approvals
        uuid: ro-2-0-1-op-s-is-009
    consequent-requests:
      - client-name: ApplicationLayerTopology://v1/update-fc
        uuid: ro-2-0-1-op-c-bm-alt-1-0-0-003
```
