### ISSUE TITLE
To include the forwarding EmbeddingStatusNotification in the CONFIG file 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#531]
For the **/v1/notify-embedding-status-changes** API , there is a callback **EmbeddingStatusNotification** specified in the **OAS**.
But , there is no forwarding defined for this callback in the CONFIG file.

**Proposal :**
kindly please consider the following proposal , 

Shall we include a callback EmbeddingStatusNotification in the CONFIG.json , forwarding.yaml

```
- forwarding-name: EmbeddingStatusNotification
    management-requests:
      operation-client-update:
        - server-name: /v1/notify-embedding-status-changes
          uuid: ro-2-1-0-op-s-is-013
    initiating-requests:
      - server-name: /v1/regard-updated-approval-status
        uuid: ro-2-1-0-op-s-is-003
    consequent-requests:
      - client-name: TAR://v1/document-embedding-status
        uuid: ro-2-1-0-op-c-im-tar-2-0-1-007
```
